from .pairwise_regularizer import PairwiseKernelRegularizer
from .nearest_neighbor_regularizer import NearestNeighborKernelRegularizer
from . import pairwise_regularizer, nearest_neighbor_regularizer